name: Android APK Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Yarn cache temizleme
    - name: Clean yarn cache
      run: yarn cache clean

    # Bağımlılıkları yükle
    - name: Install dependencies
      run: yarn install

    # Java JDK kurulumu
    - name: Install JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    # Android SDK kurulumu
    - name: Install Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: latest
        accept-android-sdk-licenses: true

    # gradlew için çalıştırma izni ver
    - name: Grant execute permission for gradlew
      run: |
        chmod +x android/gradlew
        ls -la android/gradlew  # Ekstra kontrol için

    # APK yapısını oluştur (Hata ayıklama için daha fazla bilgi ile)
    - name: Build Android APK
      run: |
        cd android
        ./gradlew assembleRelease --stacktrace --info

    # APK dosyasını yükle
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: android-apk
        path: android/app/build/outputs/apk/release/app-release.apk
